### ISSUE TITLE
bug: List and Tuple[T, ...] receives only one parameter

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#71]
MRE:
```PY
from dataclasses import dataclass
from typing import Annotated, List, Tuple

import cappa
from cappa.testing import CommandRunner

runner = CommandRunner()


@dataclass
class ArgTest:
    list_arg: Annotated[List[str], cappa.Arg(short=True, long=True)]
    tuple_arg: Annotated[Tuple[str, ...], cappa.Arg(short=True, long=True)]


t1 = cappa.parse(ArgTest, argv=['-l', '1', '-t', '2'])
print(t1)

t2 = runner.parse('-l', 'q', '--list-arg', 'w', '-t', 'e', '--tuple-arg', 'r', obj=ArgTest)
print(t2)

t3 = cappa.parse(ArgTest, argv=['-l', '1', '-t', '2', '3'])
print(t3)

t4 = cappa.parse(ArgTest, argv=['-l', '1', '2', '-t', '3', '4'])
print(t4)
```

output:
```
ArgTest(list_arg=['1'], tuple_arg=('2',))
ArgTest(list_arg=['q', 'w'], tuple_arg=('e', 'r'))
Unrecognized arguments: 3
```

comment t3:
```
ArgTest(list_arg=['1'], tuple_arg=('2',))
ArgTest(list_arg=['q', 'w'], tuple_arg=('e', 'r'))
Traceback (most recent call last):
  File "C:\Users\13522\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\scratch.py", line 25, in <module>
    t4 = cappa.parse(ArgTest, argv=['-l', '1', '2', '-t', '3', '4'])
  File "D:\git_projects\httpfpt\venv\lib\site-packages\cappa\base.py", line 71, in parse
    _, _, instance = Command.parse_command(
  File "D:\git_projects\httpfpt\venv\lib\site-packages\cappa\command.py", line 133, in parse_command
    _, parsed_command, parsed_args = backend(command, argv)
  File "D:\git_projects\httpfpt\venv\lib\site-packages\cappa\parser.py", line 81, in backend
    parse(context)
  File "D:\git_projects\httpfpt\venv\lib\site-packages\cappa\parser.py", line 265, in parse
    parse_args(context)
  File "D:\git_projects\httpfpt\venv\lib\site-packages\cappa\parser.py", line 387, in parse_args
    raw = typing.cast(RawArg, context.next_value()).raw
AttributeError: 'RawOption' object has no attribute 'raw'
```

**Comment by wu-clan** [comment]
note, cappa version: 0.10.2

**Comment by DanCardin** [comment]
I believe I fixed the traceback error as of 0.11.2

**Comment by wu-clan** [comment]
When I try 0.11.4, unfortunately the error still occurs

The only difference is.
```
t4 = cappa.parse(ArgTest, argv=['-l', '1', '2', '-t', '3', '4'])
print(t4)
```
output:
```
ArgTest(list_arg=['1'], tuple_arg=('2',))
ArgTest(list_arg=['q', 'w'], tuple_arg=('e', 'r'))
Error: Unrecognized arguments: 2
```

**Comment by DanCardin** [comment]
Well the original traceback you pasted i think was clearly a bug in prior lib versions; but the above error is expected behavior, i think.

Are you making use the functionality you're describing with either click (I'd be very surprised if click could do this) or argparse? If so, could you come up with an example of how it'd be done?

It seems to me that utilizing such a feature would mean you could only use that option at the end, or where it was followed by another option without it enabled. I.e. there'd be know way for the parser to know that the next item was another option field or a postitional argument.

For that reason, optional arguments infers consumption of **one** argument allowed infinite times. You **can** configure `num_args` on an optional to consume a **fixed** number of arguments safely, rather than just one. if for example you wanted a `list[tuple[str, str]]`, then `Annotated[list[tuple[str, str]], Arg(short=True, num_args=2)`

I suppose in theory, you might expect `list_arg: Annotated[List[str], cappa.Arg(short=True, long=True, num_args=-1)]` to work...and maybe it should. Currently you'll get a somewhat confusing (graceful) parser error.

**Comment by pawamoy** [comment]
I'm not sure I have understood you both, but here is an example that demonstrates argparse is able to handle zero or more positional arguments to options, multiple times:

```python
# parser.py
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-a", nargs="*")
parser.add_argument("-b", nargs="*")
print(parser.parse_args())
```

```console
% python parser.py -a 1 2 3 -b 4 5 6
Namespace(a=['1', '2', '3'], b=['4', '5', '6'])
```

**Comment by wu-clan** [comment]
Thanks @pawamoy for the example, it's clear!

I rarely use click, but in Typer, `Tuple[str]` is probably close to the way cappa works now, and I think click is the same, as provided in MRE, I need `-t 1 -t 2 -t 3` to pass multiple positional arguments.

**Comment by wu-clan** [comment]
In this way, it's not enough to be a bug, but rather an expected error or new functionality, Please feel free to change the title of the Issues

**Comment by DanCardin** [comment]
What I was talking about was
```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-a", nargs="*")
parser.add_argument("-b", nargs="*")
parser.add_argument("foo")
print(parser.parse_args())
```

How to you target `foo` once you've used `-a` or `-b`?
```bash
python argp.py -a 1 2 3 4
argp.py: error: the following arguments are required: foo
```

Turns out the answer is `--`. Without `--`, once you've used either `-a` or `-b`, it'd be impossible to target positional arguments. That was my main concern.

```bash
python argp.py -a 1 2 -- fo
Namespace(a=['1', '2'], b=None, foo='fo')
```

Two notes with argparse:

```bash
python argp.py -a 1 2 -a 3 4 -- 4
Namespace(a=['3', '4'], b=None, foo='4')
```

So by default that example ignores subsequent usages of option.

You can adjust to `parser.add_argument("-a", nargs="*", action="append")`, but that produces

```bash
python argp.py -a 1 2 -a 3 4 -- 4
Namespace(a=[['1', '2'], ['3', '4']], b=None, foo='4')
```

---

As I said before, i'm reasonably certain click doesn't support this: https://github.com/pallets/click/issues/2537. Which means (unless im missing something in typer) that typer doesn't support this either.

---

So with that said, I think then perhaps the expected behavior would be achieved with that i said above: `list[str], Arg(short=True, num_args=-1)`, which would give you a single option which accepts unbounded length args.

It would **not** allow you to supply that option more than once and still expect a flat list, similarly to what i'm seeing from argparse. It's not immediately obvious how to make that happen.
